repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.0
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0
    hooks:
      - id: eslint
