repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --check
        language: system
        types_or: [astro, ts, javascript, css, json, markdown, yaml]
