// Writes src/styles/fonts.css: the Latin-subset @font-face rules from the
// @fontsource packages, so pages don't carry rules for unused alphabets.
// Re-run after upgrading a font package: node scripts/build-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const sources = [
  ['@fontsource-variable/inter', 'wght.css'],
  ['@fontsource-variable/source-serif-4', 'opsz.css'],
  ['@fontsource-variable/source-serif-4', 'opsz-italic.css'],
  ['@fontsource/jetbrains-mono', '400.css'],
  ['@fontsource/jetbrains-mono', '500.css'],
];

let out =
  '/* Generated by scripts/build-fonts.mjs. Latin subsets only; do not edit. */\n';
for (const [pkg, file] of sources) {
  const css = readFileSync(`node_modules/${pkg}/${file}`, 'utf8');
  const blocks = css
    .split('/*')
    .filter((b) => /^ [\w-]+-latin-(?!ext)/.test(b));
  if (blocks.length !== 1)
    throw new Error(
      `${pkg}/${file}: expected one latin block, found ${blocks.length}`,
    );
  const block = ('/* ' + blocks[0].trim())
    .replace(/url\(\.\/files\//g, `url(../../node_modules/${pkg}/files/`)
    .replace(/,\s*url\([^)]*\.woff\)\s*format\('woff'\)/g, '');
  out += '\n' + block + '\n';
}
writeFileSync('src/styles/fonts.css', out);
console.log('wrote src/styles/fonts.css');
